[package]
name = "perf-zoo"
version = "0.1.0"
authors = ["Yao Yue <thinkingfish@gmail.com>"]
edition = "2018"

[[bin]]
name = "mutex-contention"
path = "src/mutex-contention.rs"

[[bin]]
name = "memory-alloc"
path = "src/memory-alloc.rs"

[dependencies]
structopt = "0.3"
